version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: lessonscounter_mongodb
    restart: always
    networks:
      - wedding-network
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lessonscounter_backend
    restart: always
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongodb
    networks:
      - wedding-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lessonscounter_frontend
    restart: always
    networks:
      - wedding-network
    depends_on:
      - backend

volumes:
  mongodb_data:

networks:
  wedding-network:
    name: wedding-network
